version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-magasin
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
